### ISSUE TITLE
metric does not write error with docker-compose

### ISSUE THREAD

**Issue by eturan** [c1982/swe-dashboard#2]
First of all, thank you for this repo.

I try to run it with docker-compose.

However, I get the following from swed container.

`{"level":"error","error":"GET https://gitlab.com/api/v4/merge_requests: 500 {message: 500 Internal Server Error}","metric":"selfmerging","time":"2022-02-16T18:41:43Z","message":"metric does not write"}`

Any idea what might be the problem and how to fix it?

PS: I have tried with full permission Gitlab Access Token

**Comment by c1982** [comment]
Thanks @eturan,

Just tested on on-prem gitlab CE. Sorry, I've never tested on gitlab.com yet. 

I have no idea. 🤷‍♂️

**Comment by eturan** [comment]
No worries I will take a look at it and send PR if I find a solution.

Any useful tricks to debug it?

**Comment by c1982** [comment]
We use https://github.com/xanzy/go-gitlab package for Gitlab Client. Error is returned from this package. 
Otherwise
